
package oopfinalproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    /** Creates new form Register */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegiserPanel1 = new javax.swing.JPanel();
        roundedTextField1 = new oopfinalproject.RoundedTextField();
        roundedPasswordField1 = new oopfinalproject.RoundedPasswordField();
        roundedButton1 = new oopfinalproject.RoundedButton();
        roundedButton2 = new oopfinalproject.RoundedButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegiserPanel1.setBackground(new java.awt.Color(26, 26, 26));
        RegiserPanel1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        RegiserPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        roundedTextField1.setBackground(new java.awt.Color(242, 242, 242));
        roundedTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(116, 252, 51), 1, true));
        roundedTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        roundedTextField1.setText("   Username");
        roundedTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        roundedTextField1.setFont(new java.awt.Font("SF UI  Text", 0, 12)); // NOI18N
        roundedTextField1.setRadius(25);
        roundedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roundedTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                roundedTextField1FocusLost(evt);
            }
        });
        roundedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedTextField1ActionPerformed(evt);
            }
        });

        roundedPasswordField1.setBorder(null);
        roundedPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        roundedPasswordField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        roundedPasswordField1.setText("   Password");
        roundedPasswordField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        roundedPasswordField1.setEchoChar('\u0000');
        roundedPasswordField1.setFont(new java.awt.Font("SF UI  Text", 0, 12)); // NOI18N
        roundedPasswordField1.setRadius(25);
        roundedPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roundedPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                roundedPasswordField1FocusLost(evt);
            }
        });
        roundedPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedPasswordField1ActionPerformed(evt);
            }
        });

        roundedButton1.setBackground(new java.awt.Color(102, 102, 102));
        roundedButton1.setBorder(null);
        roundedButton1.setForeground(new java.awt.Color(255, 255, 255));
        roundedButton1.setText("LOGIN");
        roundedButton1.setBackgroundColor(new java.awt.Color(51, 51, 51));
        roundedButton1.setBorderColor(new java.awt.Color(116, 252, 51));
        roundedButton1.setContentAreaFilled(false);
        roundedButton1.setFont(new java.awt.Font("SF UI  Text Light", 0, 14)); // NOI18N
        roundedButton1.setHoverColor(new java.awt.Color(116, 252, 51));
        roundedButton1.setMaximumSize(new java.awt.Dimension(45, 18));
        roundedButton1.setMinimumSize(new java.awt.Dimension(45, 18));
        roundedButton1.setRadius(25);
        roundedButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedButton1MouseClicked(evt);
            }
        });
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });

        roundedButton2.setBackground(new java.awt.Color(102, 102, 102));
        roundedButton2.setBorder(null);
        roundedButton2.setForeground(new java.awt.Color(255, 255, 255));
        roundedButton2.setText("REGISTER");
        roundedButton2.setBackgroundColor(new java.awt.Color(51, 51, 51));
        roundedButton2.setBorderColor(new java.awt.Color(116, 252, 51));
        roundedButton2.setContentAreaFilled(false);
        roundedButton2.setFont(new java.awt.Font("SF UI  Text Light", 1, 14)); // NOI18N
        roundedButton2.setHoverColor(new java.awt.Color(116, 252, 51));
        roundedButton2.setMaximumSize(new java.awt.Dimension(45, 18));
        roundedButton2.setMinimumSize(new java.awt.Dimension(45, 18));
        roundedButton2.setPreferredSize(new java.awt.Dimension(42, 18));
        roundedButton2.setRadius(25);
        roundedButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopfinalproject/2BG.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("GothamSSm", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Create an account!");

        javax.swing.GroupLayout RegiserPanel1Layout = new javax.swing.GroupLayout(RegiserPanel1);
        RegiserPanel1.setLayout(RegiserPanel1Layout);
        RegiserPanel1Layout.setHorizontalGroup(
            RegiserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegiserPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(RegiserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(roundedButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(71, 71, 71))
        );
        RegiserPanel1Layout.setVerticalGroup(
            RegiserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegiserPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegiserPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegiserPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void roundedTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roundedTextField1FocusGained
        // TODO add your handling code here:
        if(roundedTextField1.getText().equals("   Username"))
        {
            roundedTextField1.setText("");
            roundedTextField1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_roundedTextField1FocusGained

    private void roundedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roundedTextField1FocusLost
        // TODO add your handling code here:
        if(roundedTextField1.getText().equals(""))
        {
            roundedTextField1.setText("   Username");
            roundedTextField1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_roundedTextField1FocusLost

    private void roundedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedTextField1ActionPerformed

    private void roundedPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roundedPasswordField1FocusGained
        // TODO add your handling code here:
        if(String.valueOf(roundedPasswordField1.getPassword()).equals("   Password"))
        {
            roundedPasswordField1.setText("");
            roundedPasswordField1.setForeground(new Color(153,153,153));
            roundedPasswordField1.setEchoChar('*');
        }

    }//GEN-LAST:event_roundedPasswordField1FocusGained

    private void roundedPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roundedPasswordField1FocusLost
        // TODO add your handling code here:
        if(String.valueOf(roundedPasswordField1.getPassword()).equals(""))
        {
            roundedPasswordField1.setEchoChar((char)0);
            roundedPasswordField1.setText("   Password");
            roundedPasswordField1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_roundedPasswordField1FocusLost

    private void roundedPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedPasswordField1ActionPerformed

    private void roundedButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedButton1MouseClicked

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        // TODO add your handling code here:
            loggedInUsername();
            
    }//GEN-LAST:event_roundedButton1ActionPerformed

    private void roundedButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton2ActionPerformed
        // TODO add your handling code here:
        Register RegiserPanel = new Register();
        RegiserPanel.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_roundedButton2ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }
public String loggedInUsername() {
    String Username = roundedTextField1.getText();
    String Password = new String(roundedPasswordField1.getPassword()); // Assumes you're using a JPasswordField

    // Validate inputs
    if (Username.isEmpty() || Password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username and password are required.");
        return null;
    }

    String loggedInUsername = null;

    // Validate username and password with the database
    try (Connection con = MyConnection.getConnection()) {
        String sql = "SELECT * FROM register WHERE Username = ? AND Password = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, Username);
        ps.setString(2, Password); 

        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            loggedInUsername = rs.getString("Username");  
            UserSession.setLoggedInUsername(loggedInUsername);  // Store the username in UserSession

            JOptionPane.showMessageDialog(this, "Login successful!");

            // Open the next interface
            Dashboard jLayeredPane1 = new Dashboard();
            jLayeredPane1.setVisible(true);
            this.dispose();  // Close current window
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.");
        }
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }

    return loggedInUsername;  // Return the logged-in username if needed
        }
    
public class UserSession {
    private static String loggedInUsername;

    public static void setLoggedInUsername(String username) {
        loggedInUsername = username;
    }

    public static String getLoggedInUsername() {
        return loggedInUsername;
    }
    
    public static void clear() {
        loggedInUsername = null; // Clear session data
    }

        static void setLoggedInUsername() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RegiserPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private oopfinalproject.RoundedButton roundedButton1;
    private oopfinalproject.RoundedButton roundedButton2;
    private oopfinalproject.RoundedPasswordField roundedPasswordField1;
    private oopfinalproject.RoundedTextField roundedTextField1;
    // End of variables declaration//GEN-END:variables

}
